version: '3.8'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_DATABASE: "AdultEaseDB"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

volumes:
  db-data:
